# Generated by Django 3.2.23 on 2023-12-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Content',
        ),
    ]
